### ISSUE TITLE
Rojo crashed after attempting to build a binary Roblox model file

### ISSUE THREAD

**Issue by Jaguar-515** [rojo-rbx/rojo#279] opened 2019-12-12 23:54 UTC
After I used `rojo build --output plugin.rbxm` to build a plugin in binary format, the thread main panicked at 'not yet implemented'.

default.project.json:
```
{
  "name": "CoreGui-Manager",
  "servePort": 34872,
  "tree": {
    "$className": "DataModel",
    "ServerScriptService": {
      "$className": "ServerScriptService",
      "CoreGui-Manager": {
        "$path": "src"
      }
    }
  }
}
```

Error:
```
thread 'main' panicked at 'not yet implemented', C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\rbx_binary-0.4.1\src\serializer.rs:160:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[ERROR rojo] Rojo crashed!
[ERROR rojo] This is a bug in Rojo.
[ERROR rojo]
[ERROR rojo] Please consider filing a bug: https://github.com/LPGhatguy/rojo/issues
[ERROR rojo]
[ERROR rojo] Details: not yet implemented
```

Note that the folder name in C:\Users is undisclosed due to privacy reasons.

**Comment by LPGhatguy** [comment] 2019-12-13 00:06
Thanks for reporting a bug like the CLI asked!

The project that you're posting appears to be a game (`rbxl`), but you also mentioned building this as a plugin (`rbxm`).

Building a binary _place_ was reported in #140. We since added a warning that tells you that building binary places is likely to have problems:

![image](https://user-images.githubusercontent.com/654598/70758777-dc32b800-1cf8-11ea-8023-3da38ff50b65.png)

Building binary models is more interesting. As noted in #180, support for the binary model format is still pretty poor, including the symptoms you're seeing. We don't warn for binary models since they're less likely to contain properties that Rojo doesn't know about.

We're still actively working on this, but I'm going to go ahead and close this issue as a duplicate of #180, as well as rojo-rbx/rbx-dom#26. If you've got more feedback or issues that you hit building binary models besides this one, that's the place to be!

**Closed** 2019-12-13 00:06 UTC
Labels: duplicate
