### ISSUE TITLE
rojo serve failing to sync large files

### ISSUE THREAD

**Issue by magicgong** [rojo-rbx/rojo#457] opened 2021-07-26 01:35 UTC
Received this warning: 

[Rojo-Warn] Could not apply all changes requested by the Rojo server:
[Rojo-Warn] - Update properties on path.to.file

My filesize is 388 KB, having ~16 KLOCs

Steps to reproduce:

1. Attempt to sync a file with 4 KLOCs -- works fine.
2. Attempt to sync a file with 16 KLOCs -- receive the warning, doesn't work.

**Comment by Kampfkarren** [comment] 2021-07-26 01:45
Plugins can only edit script sources to be 200k character long. It is not possible for Rojo to serve them, though `rojo build` will work.

**Comment by LPGhatguy** [comment] 2021-07-26 16:24
Hello, thanks for filing an issue.

I am closing this as a duplicate of #438. This is something we've seen reported time and time again, but it's hard for us to fix.

**Closed by LPGhatguy** 2021-07-26 16:24 UTC
