### ISSUE TITLE
Auto connect/sync projects after serve

### ISSUE THREAD

**Issue by Boegie19** [rojo-rbx/rojo#598] opened 2022-07-30 13:04 UTC
# Auto connect/sync projects after serve

if #588 where to pass then the plugin will be scanning the local host anyway.

So way not make an auto connect feature in the plugin.

requirements to auto connect would be in the project.json file
`$servePlaceIds` list includes the id of the current project 
`$autoSync` = true 

requirements in the plugin would be
`Auto sync` setting should be true. (this should default to false)

Only if all requirements are fulfilled then it will auto connect to the place

**Comment by LPGhatguy** [comment] 2022-08-03 23:42
Closing as a duplicate of #362.

**Closed by LPGhatguy** 2022-08-03 23:42 UTC
