### ISSUE TITLE
Weird chars after sync if text contains UTF-8 symbols

### ISSUE THREAD

**Issue by foxfabi** [rojo-rbx/rojo#444] opened 2021-07-11 17:26 UTC
Saving a [text button](https://developer.roblox.com/en-us/api-reference/class/TextButton) containing an [UTF-8 miscellaneous symbol](https://www.utf8-chartable.de/unicode-utf8-table.pl?start=9728) as Roblox XML Model File results in weird chars after sync. 

![rojo-issue2](https://user-images.githubusercontent.com/785565/125204375-3bfa9780-e27d-11eb-91f9-6ec1e202eda8.png)
![rojo-issue](https://user-images.githubusercontent.com/785565/125204377-3c932e00-e27d-11eb-8b6e-4d1be763b4e9.png)

I'm using:
* Visual Studio Code 1.58.0 (system setup) on windows
* Rojo 6.1.0
* Roblox Studio 0.485.0.425755 (64bit) / Latest version available 0.485.0.425755

**Comment by LPGhatguy** [comment] 2021-07-11 23:29
Hello, thank you for the report! I'm sorry that you're running into this.

I am closing this as a duplicate of #379. This is something that we still need to investigate and fix.

**Closed by LPGhatguy** 2021-07-11 23:29 UTC
