### ISSUE TITLE
Property values that are set as inf in Roblox cause issues

### ISSUE THREAD

**Issue by ayuka** [rojo-rbx/rojo#467] opened 2021-08-09 17:58 UTC
This is using a modified version of the Rojo plugin to print the property name and instance when type is nil. It seems that Rojo doesn't correctly parse it and produces an empty property value table.

Here's a reproduction file, you should only need to open the place file and sync: [infbug.zip](https://github.com/rojo-rbx/rojo/files/6956393/infbug.zip)

```
  12:55:48.311  MaxDistance gui  -  Edit
  12:55:48.311  [Rojo-Warn] Failed to decode property of type nil  -  Edit
```

**Comment by LPGhatguy** [comment] 2021-10-15 18:13
Hello, thank you for the bug report!

I am closing this as a duplicate of #363.

**Closed by LPGhatguy** 2021-10-15 18:13 UTC
