### ISSUE TITLE
rojo build doesn't work for Int32 and Int64

### ISSUE THREAD

**Issue by RuizuKun-Dev** [rojo-rbx/rojo#927] opened 2024-06-15 05:06 UTC
whenever I'm using Rojo build if an init.meta.json has an Attribute that is an Int32 or Int64 I'd get an error, although I'm assuming this is expected behavior since Attributes only has Number and not Integer type

**Comment by Dekkonot** [comment] 2024-06-15 05:11
This is expected behavior, though it's something I want to make better. The expected type for numbers is `Float64` since that's what Luau numbers are.

This is an upstream problem with https://github.com/rojo-rbx/rbx-dom, but not a bug per se. Going to close this and if you want you can open an issue on rbx-dom asking us to support Int32/Int64 for attributes.

**Closed by Dekkonot** 2024-06-15 05:11 UTC
Labels: type: support
