### ISSUE TITLE
macOS HTTP Error

### ISSUE THREAD

**Issue by LuxxeOfficial** [rojo-rbx/rojo#782] opened 2023-09-11 16:49 UTC
Unknown HTTP error: Number of requests exceeded limit

<img width="739" alt="image" src="https://github.com/rojo-rbx/rojo/assets/85503367/5f197b35-18f0-4201-999c-ad8c261dc2dc">

This issue happens sporadically during development, as well as some times when i just click connect. Not an issue with the project, as on my home windows computer it does not suffer this same issue. Using default rojo settings.

**Comment by kennethloeffler** [comment] 2023-09-11 23:16
Hi,

Roblox recently made some changes to HttpService that could be causing this problem. We aren't yet sure what's going wrong exactly, but we're working on it!

Also, can you please confirm that two-way sync is NOT enabled in the settings page?

**Comment by LuxxeOfficial** [comment] 2023-09-13 02:42
Two way sync is not enabled.

**Comment by boatbomber** [comment] 2023-09-19 01:07
Closing as duplicate of https://github.com/rojo-rbx/rojo/issues/781, since that one came first. I will be reposting these messages there as they do add helpful info!

**Closed by boatbomber** 2023-09-19 01:07 UTC
