### ISSUE TITLE
Rojo crash on start, $className or $path missing from option.rs, vs-code plugin

### ISSUE THREAD

**Issue by DylWithlt** [rojo-rbx/rojo#436] opened 2021-06-26 18:36 UTC
```
[ERROR] Rojo crashed!
[ERROR] This is probably a Rojo bug.
[ERROR] 
[ERROR] Please consider filing an issue: https://github.com/rojo-rbx/rojo/issues
[ERROR] 
[ERROR] Details: $className or $path must be specified
[ERROR] in file src\libcore\option.rs on line 1188
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by LPGhatguy** [comment] 2021-06-26 19:29
Duplicate of #423. This has been fixed for Rojo 7.0. Try the alpha, if you're interested!

**Closed by LPGhatguy** 2021-06-26 19:29 UTC
Labels: duplicate
