### ISSUE TITLE
Moto6D "Part0" and "Part1" properties not being filled on build

### ISSUE THREAD

**Issue by grilme99** [rojo-rbx/rojo#346] opened 2020-07-20 15:36 UTC
When building a Rojo project into a `.rbxlx`, the `Motor6D` `Part0` and `Part1` properties do not get filled. This results in broken character rigs in my game and prevents me from using a Fully Managed Rojo setup.

To repo this issue, use the attached file (had to put it into a ZIP) and build the project with `rojo build`. Meshes load fine as expected, but joints are broken.

[CharacterTemplate.zip](https://github.com/Roblox/rojo/files/4948668/CharacterTemplate.zip)

**Comment by LPGhatguy** [comment] 2020-07-20 18:23
Hello! This is a duplicate of #142, which was fixed for building in Rojo 6.0.0-rc.1.

**Comment by vsDizzy** [comment] 2020-08-11 10:16
I'm using rc1 and synchronizing .rbxmx model under workspace folder. Welds `Part0` and `Part1` properties are empty.
![image](https://user-images.githubusercontent.com/5798340/89886083-b980d800-dbd4-11ea-83ed-1c7cc7d2cb9b.png)

Here is the model
[heli.zip](https://github.com/Roblox/rojo/files/5056344/heli.zip)

**Comment by LPGhatguy** [comment] 2020-09-10 01:01
@vsDizzy While Rojo 6.0.0-rc.1 has support for _building_ places with referents in them, it still doesn't have support for live syncing them.

That should be resolved by #332.

**Closed by LPGhatguy** 2020-09-10 01:01 UTC
Labels: duplicate, type: bug
