### ISSUE TITLE
Changes to symlinked files do not sync

### ISSUE THREAD

**Issue by tonycuadra** [rojo-rbx/rojo#470] opened 2021-08-17 16:35 UTC
Files that are served by Rojo via symlinked folders do not update automatically when the file contents change. Connecting again to Rojo from an empty data model will pull in old cached versions of the files that no longer exist on disk. Only stopping and restarting the Rojo server will update linked files.

**Comment by LPGhatguy** [comment] 2021-08-23 19:33
Hey, thanks for filing a bug!

I believe this is a duplicate of #278. Handling symlinks is tricky to do well, and the behavior is different on some platforms even! I am going to close this as a duplicate.

**Closed by LPGhatguy** 2021-08-23 19:33 UTC
Labels: type: bug
