### ISSUE TITLE
Two-Way Sync causing instant crash upon connecting

### ISSUE THREAD

**Issue by Meqolo** [rojo-rbx/rojo#329] opened 2020-06-20 11:57 UTC
When connecting to a rojo server with two-way sync enabled, it results in the server crashing with this error 100% of the time: 
![image](https://user-images.githubusercontent.com/45327591/85201235-a39e1780-b2f5-11ea-8967-70d4ce4ed057.png)

**Comment by Dionysusnu** [comment] 2020-07-04 15:39
that's this line: `fs::write(path, value).unwrap()`.
maybe your folder is read-only?

**Comment by kennethloeffler** [comment] 2024-03-30 22:15
Closing this as a duplicate of #790 since there's more information there

**Closed by kennethloeffler** 2024-03-30 22:15 UTC
Labels: type: bug, two-way-sync
