### ISSUE TITLE
Rojo does not properly set an exit code if an error occurs

### ISSUE THREAD

**Issue by Reshiram110** [rojo-rbx/rojo#319] opened 2020-05-11 16:31 UTC
Currently in rojo `6.0.0-rc.1`, rojo does not throw an exit code above 0 (e.g. exit code 1) if an error occurs while running a command. For example, if a non-existent file is specified in `*.project.json` and `rojo build` is ran, rojo will throw a 'file not found' error, but the exit code is not set above 0:
```
PS > rojo build -o CurrentBuild.rbxlx testenv.project.json
[ERROR] failed to query metadata of file `<PathToRepo>\./src/Server/Utilss`
[ERROR]   caused by The system cannot find the file specified. (os error 2)
PS > Write-Output $LASTEXITCODE
0
```
This makes it impossible for windows powershell/batch scripts to run conditional logic if a rojo build fails.

**Comment by LPGhatguy** [comment] 2020-06-17 21:57
Hello!

I was not able to reproduce this issue. I believe you also use [Foreman](https://github.com/rojo-rbx/foreman), which had a bug that was recently fixed for propagating error codes (https://github.com/rojo-rbx/foreman/pull/20).

As such, I'm going to close this issue. If you have a repro for this with either 6.0.0-rc.1 or the master branch _without_ Foreman, feel free to re-open this issue! If it only occurs with Foreman, definitely open an issue over there.

Thanks!

**Closed by LPGhatguy** 2020-06-17 21:57 UTC
Labels: regression, type: bug
