### ISSUE TITLE
Multiple developers w/ Rojo - script conflicts ?

### ISSUE THREAD

**Issue by general-adhoc** [rojo-rbx/rojo#394] opened 2021-02-05 09:06 UTC
We recently finished setting up partially managed Rojo (all scripts, no models), with the intention of having developers and builders work out of one "master" place per environment (dev, prod), and committing their script changes only after merging their feature branch into "master"

The issue we're running into, is that Rojo is syncing files on save and not commit.  This was probably from our misunderstanding, as we thought with team create enabled you'd still get the commit draft changes prompt.  Rojo appears to bypass team create altogether.  So as soon as a dev hits "save" in their external editor, it's live in studio for everyone to see.

Spent a few hours reading every topic on the roblox forums with the word "rojo" in it, and came close [here ](https://devforum.roblox.com/t/teams-that-use-rojo-git-what-is-your-workflow/680785/2) but still can't figure out how to set this up correctly.

We want developers to be able to test changes on their machine before having the changes go live for everyone else to see, and have rojo sync them into the "live" version of dev/prod/etc only when committed/merged.  We need one shared world for models though as our game world is quite complex and fully-managed rojo is impractical for us due to the volume of changes / additions on a daily basis, at least for the time being.  

What happens when two developers are editing the same script file? A workaround I know some teams use is have each developer each work in their own version of the game world, but since it's partially managed, how would we go about merging in model / other asset changes, especially if there are conflicts?  You couldn't have each developer re-publish their world into "master" as that could possibly wipeout other model/asset changes.

Any guidance is extremely appreciated.

**Comment by LPGhatguy** [comment] 2021-02-16 04:21
Hi, thanks for reaching out!

Generally, Rojo is not compatible with Team Create and multiple scripters. The Rojo Roblox Studio plugin isn't able to interact with Team Create's drafts system, so they usually end up fighting each other.

I suggest using multiple places, Git, and optionally VS Code Live Share for collaboration on code when using Rojo. This gives everyone their own place to work in without stepping on anyone else. It's what my current team working on Adopt Me does, and it works fairly well!

For merging non-code changes, the strategy Adopt Me uses is pretty simple. We maintain a test place that has the latest updates to models that we periodically save over our test places. From there, we use Rojo to sync in the latest code and we're off to the races!

We're working on making it possible to automate that workflow with another tool, [Remodel](https://github.com/rojo-rbx/remodel). The master branch is almost working to do this, but isn't there quite yet!

I would love to codify a lot of this into a page in the documentation, but I never seem to have time. A lot of teams run into this problem and it would be good to have a central place for guidance.

**Comment by Logodaedalus** [comment] 2021-03-18 19:38
Just to be 100% sure, is it expected behavior that this happens if you have Team Create enabled for people to edit the scene, but have Collaborative Editing turned off for scripts? Not even two people editing the same script...for example if:
1. two people are in a Team Create instance, and both are connected via Rojo
2. one person saves coolGameScript.lua in VSCode, accidentally introducing an error. They don't commit or do anything else.
3. the other person runs the game, and sees the error, because their copy of coolGameScript.lua in the Roblox editor was updated as soon as person one hit save in VSCode

**Comment by DanielFeyghin** [comment] 2021-08-16 10:47
> Hi, thanks for reaching out!
> 
> Generally, Rojo is not compatible with Team Create and multiple scripters. The Rojo Roblox Studio plugin isn't able to interact with Team Create's drafts system, so they usually end up fighting each other.
> 
> I suggest using multiple places, Git, and optionally VS Code Live Share for collaboration on code when using Rojo. This gives everyone their own place to work in without stepping on anyone else. It's what my current team working on Adopt Me does, and it works fairly well!
> 
> For merging non-code changes, the strategy Adopt Me uses is pretty simple. We maintain a test place that has the latest updates to models that we periodically save over our test places. From there, we use Rojo to sync in the latest code and we're off to the races!
> 
> We're working on making it possible to automate that workflow with another tool, [Remodel](https://github.com/rojo-rbx/remodel). The master branch is almost working to do this, but isn't there quite yet!
> 
> I would love to codify a lot of this into a page in the documentation, but I never seem to have time. A lot of teams run into this problem and it would be good to have a central place for guidance.

My team and I ran exactly into what the OP wrote since we recently picked up Rojo. Could you please clarify what do you mean by "we use Rojo to sync in the latest code" ?
do you keep 2 places synced to two separate folders? do you move between said folders the updated code? do you keep 2 Git repos synced 1 for local and 1 for the "live" version? How exactly do you update the code of the place with the latest models using Rojo?

**Comment by boatbomber** [comment] 2023-06-02 18:51
The issue of script conflicts from multiple syncing users has been resolved by #590.

**Closed by boatbomber** 2023-06-02 18:51 UTC
Labels: type: support
