### ISSUE TITLE
Rojo v7.4.2 corrupts refs, meshes & part positions

### ISSUE THREAD

**Issue by NobleDraconian** [rojo-rbx/rojo#953] opened 2024-07-30 01:57 UTC
Currently, as of rojo `v7.4.2`, refs (e.g. `HingeConstraint.Attachment0`), certain meshes (`MeshID` it seems), and part positions for certain models get corrupted upon serving. `rojo build` does not have this problem.

I've attached a repro file to this issue as a ZIP.

To reproduce, extract the contents of the zip into a folder, then:
1) `rojo build default.project.json -o place.rbxl`
2) Open the place file
3) Move the camera to the `Map` model. Observe the obstacle model appears fine.
4) `rojo serve default.project.json` & connect the rojo plugin to the server.
5) Observe the model corrupts. Parts get mispositioned, refs are set to `nil` with warnings being spit from the output, and meshes sometimes revert to the standard cube shape when no mesh ID is present.

[RojoRepro.zip](https://github.com/user-attachments/files/16420868/RojoRepro.zip)

![image](https://github.com/user-attachments/assets/c53aaea3-a002-4ad3-b0ea-0a594d72d163)
![image](https://github.com/user-attachments/assets/c492ca51-4f31-4ffd-aed0-45d16712d4f0)

**Comment by Dekkonot** [comment] 2024-07-30 02:05
I suspect this is a problem with the plugin based on a previous report. Can you downgrade to the 7.4.1 plugin and check if it has this problem?

**Comment by NobleDraconian** [comment] 2024-07-30 02:06
Sure, will report back in a minute with the results.

**Comment by NobleDraconian** [comment] 2024-07-30 02:08
@Dekkonot Downgrade the plugin only, not rojo itself?

**Comment by Dekkonot** [comment] 2024-07-30 02:10
Yes. If we can determine if it's a server or plugin change, it'd help a lot with diagnosing the problem.

**Comment by NobleDraconian** [comment] 2024-07-30 02:12
I just tested the repro with Plugin version `7.4.1` and rojo version `7.4.2`, the results were the same.

**Comment by Dekkonot** [comment] 2024-07-30 02:14
Going to hesitantly mark this a CLI bug then. Thank you, I'll take a look soon.

**Comment by NobleDraconian** [comment] 2024-07-30 02:30
OH, one piece of information I forgot to include! Plugins were installed via `rojo plugin install`.

**Comment by kennethloeffler** [comment] 2024-07-31 16:07
Do you see any of the "Failed to decode property" or "value of type nil cannot be converted to a number" warnings when you follow your repro steps? I can see the parts become mispositioned after step 4, but I don't see any warnings or meshes changing

**Comment by NobleDraconian** [comment] 2024-07-31 18:57
@kennethloeffler Not with the repro I provided. For some odd reason, those warnings only seem to occur when the entirety of my assets folder is present. The model I provided is one of the models that was causing the warning, but on its own it doesn't generate one.

**Comment by kennethloeffler** [comment] 2024-07-31 19:37
If making an isolated repro for those is difficult, would you be comfortable with sharing your project privately? You can contact me on Discord @ken.loeffler or email me at kenloef@gmail.com

**Comment by NobleDraconian** [comment] 2024-07-31 21:01
@kennethloeffler I'll see what I can do! I'm about to make dinner, so I'll have the zip for you in about 1-2 hours.

**Comment by NobleDraconian** [comment] 2024-08-01 00:01
@kennethloeffler I've emailed you the RBXM file!

**Comment by kennethloeffler** [comment] 2024-08-01 14:43
Thanks - I believe I was able to isolate the cause of the problem using your provided file, and I've prepared a fix. Would you mind testing it out @NobleDraconian? You can find it at https://github.com/kennethloeffler/rojo/releases/tag/v7.4.2-rbx-binary-postorder. If you're using Aftman or Rokit, you should be able to install it with:
```toml
rojo = "kennethloeffler/rojo@7.4.2-rbx-binary-postorder"
```
Or with Foreman:
```toml
rojo = { github = "kennethloeffler/rojo", version = "7.4.2-rbx-binary-postorder" }
```

**Comment by NobleDraconian** [comment] 2024-08-01 15:19
@kennethloeffler Your build of rojo fixes the issue! I didn't notice any corruption with it.

However, the `value of type nil cannot be converted to a number` warning still occurs on initial sync.

**Comment by kennethloeffler** [comment] 2024-08-01 15:30
If you feel up for modifying your plugin slightly, we can investigate this more deeply. In the plugin's PropertyDescriptor module, there's a branch taken when a property write fails due to an error: 
https://github.com/rojo-rbx/rojo/blob/844f51d91698bea8fa7483eb12e319f6afe23d87/plugin/rbx_dom_lua/PropertyDescriptor.lua#L75-L84

If you add something like
```luau
print(instance:GetFullName(), self.className, self.name, value)
```
just after the `else` at line 81, try the initial sync again, then post the results here, then we hopefully can understand this a little better!

**Comment by NobleDraconian** [comment] 2024-08-01 16:15
I modified the plugin, but the print does not occur:
![image](https://github.com/user-attachments/assets/a6f0f861-2efa-44fe-920a-478f4a1d8ccd)

**Comment by kennethloeffler** [comment] 2024-08-01 16:30
Strange, maybe this particular property set is warning instead of erroring in this scenario, so xpcall is returning true...? 🤔 

At any rate, you could try printing out *everything* (i.e. move the print just before the xpcall at line 77), which will massively spam your output (turning on "log mode" could help with performance there), but we should be able to see the failing property get printed out before these warnings

**Comment by Dekkonot** [comment] 2024-08-01 16:44
I'm able to confirm that your release fixes the issues with `rojo build` followed by `rojo serve`. Why? I have no idea. I wonder what kind of implicit ordering we're running into here.

In terms of the plugin trouble, it turns out that the issue we're running into *isn't an error*, which is why it's not being emitted with xpcall. I've been able to identify `AlignOrientation.MaxAngularVelocity` and `AlignPosition.MaxVelocity` as the problem children here. You should be able to confirm this by checking the patch visualizer and confirming that they're changing from a non-nil value to `nil`. In my test it was from `inf` to `nil`.

**Comment by kennethloeffler** [comment] 2024-08-01 16:54
Infinities aren't correctly encoded by Rojo, so that makes sense. I'd expect this to happen for any property whole value is `inf`, `-inf`, or `NaN`, like in #363. Is it possible that this was being silently ignored in whatever version NobleDraconian was using previously?

**Comment by Dekkonot** [comment] 2024-08-01 17:01
Right, that makes sense. I suppose the question becomes do we want to do anything about it then? I'm guessing no, not in this release.

We could change the plugin to casually ignore `nil` values for number properties. It'd silence the warning, but I'd be worried about leaving it there for too long. Temporary fixes have a way of becoming permanent if you're not careful and all that.

**Comment by kennethloeffler** [comment] 2024-08-01 17:26
Yeah, it sounds like a good idea to put in some nil checks for Float64 and Float32 values, so that Rojo doesn't mess them up after building and syncing, at least. When you try to set a number property to nil, it prints a warning (bad) and actually gets set to 0 (very bad)! We can check the property type, and if it's a float and the value is nil, then bail immediately and don't attempt to set the property.

However, this simple approach won't work for infinities or NaNs in compound types like UDim or Vector2. Do we care about working around those as well? Maybe we should only do it for very common cases, like Vector2 (which is commonly set as `inf, inf` on UiSizeConstraint.MaxSize)?

If we don't want this workaround to stick around for long, then we should only do it on the 7.4.x branch and leave everything else alone. We'll just need to make sure to properly fix the encoding problem before the next major or minor release

**Comment by Dekkonot** [comment] 2024-08-01 17:46
Would you blame me if I said I'm more interested in silencing the warning than I am about fixing the behavior in this patch? While the existing behavior for compound types is unintuitive, it's also not new and I think that makes it fine to leave for now.

**Comment by kennethloeffler** [comment] 2024-08-01 17:59
Yeah, that's fine. If you want to take care of this warning, then I can make a PR and dive into why post-order traversal works for rbx_binary, also follow up with badcc to confirm that they no longer see problems, and then we can make a 7.4.3 release

**Comment by Dekkonot** [comment] 2024-08-08 15:14
A release was made with the fix for this a few days ago. Forgot to close this issue:
https://github.com/rojo-rbx/rojo/releases/tag/v7.4.3

**Closed by Dekkonot** 2024-08-08 15:14 UTC
Labels: type: bug, scope: cli, impact: high, version 7.4
