### ISSUE TITLE
"inf" values convert to 0 (Rojo 7)

### ISSUE THREAD

**Issue by chexburger** [rojo-rbx/rojo#498] opened 2021-11-04 23:14 UTC
Rojo 7 is encountering a bug with UISizeConstraints and probably more classes. The MaxSize and MinSize convert `inf` values to zero, rather than back to `inf`.

This interface is exported to `rbxm` and imported back through Rojo.
![image](https://user-images.githubusercontent.com/15860911/140433016-489e9a3b-fe3f-4e88-8f50-d4122e318ba8.png)

**Comment by LPGhatguy** [comment] 2021-11-12 02:24
Hello!

This is a known issue in Rojo's sync protocol. You can use `rojo build` to ensure these values are built correctly while we work on a fix.

This is a duplicate of #363.

**Closed by LPGhatguy** 2021-11-12 02:24 UTC
