### ISSUE TITLE
Attribute Support

### ISSUE THREAD

**Issue by fuzzy-bit** [rojo-rbx/rojo#514] opened 2021-12-23 17:26 UTC
In my module loading framework, I use attributes to load modules in order. This is currently impossible in Rojo, and I think it should be implemented in one way or another. A good way to implement attributes for scripts would be to have a JSON file with the same name as the file (w/o extension) and associate them that way. Project files could also disable this feature.

**Comment by Ozzypig** [comment] 2022-03-08 23:37
Duplicate of #262

**Comment by fuzzy-bit** [comment] 2022-03-09 20:19
Ah, didn't see.

**Closed** 2022-03-11 00:46 UTC
Labels: duplicate
