### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by DeadOfAutumn** [rojo-rbx/rojo#442] opened 2021-07-06 00:00 UTC
``Visit http://localhost:34872/ in your browser for more information.
[ERROR] Rojo crashed!
[ERROR] This is probably a Rojo bug.
[ERROR]
[ERROR] Please consider filing an issue: https://github.com/rojo-rbx/rojo/issues
[ERROR]
[ERROR] Details: error binding to 12...:34872: error creating server listener: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
[ERROR] in file C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.12.36\src\server\mod.rs on line 116   
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
PS C:\Users\Br...\Desktop\nidorx\roblox-rojo-bundle\build> rojo serve
Rojo server listening:
  Address: localhost
  Port:    34872

Visit http://localhost:34872/ in your browser for more information.
[ERROR] Rojo crashed!
[ERROR] This is probably a Rojo bug.
[ERROR]
[ERROR] Please consider filing an issue: https://github.com/rojo-rbx/rojo/issues
[ERROR]
[ERROR] Details: error binding to 12...:34872: error creating server listener: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
[ERROR] in file C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.12.36\src\server\mod.rs on line 116   
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
PS C:\Users\Br...\Desktop\nidorx\roblox-rojo-bundle\build>``

**Comment by ShaneButt** [comment] 2021-07-06 15:05
You already have rojo running or something else is using the socket address hence rojo cannot start up. You can go to the link specified (http://localhost:34872/) to view where rojo is currently running (if it's rojo using the port).

**Comment by LPGhatguy** [comment] 2021-07-12 16:45
What @ShaneButt mentioned here is correct. You have another server running on the same port that Rojo is trying to use. We're unable to catch this error for whatever reason, so there's not much we can do right now.

I am closing this as a duplicate of #302.

**Closed by LPGhatguy** 2021-07-12 16:45 UTC
