### ISSUE TITLE
Studio Freezes After Updating in VSCode

### ISSUE THREAD

**Issue by joego2124** [rojo-rbx/rojo#354] opened 2020-09-11 03:39 UTC
Roblox studio will freeze when pressing play solo after saving a file in VSCode.

**Comment by LPGhatguy** [comment] 2020-10-05 23:33
Hello, thank you for the bug report!

What version of Rojo are you seeing this issue on? Is there a place you can share that demonstrates this issue to help in tracking it down?

Rojo does not intentionally interact with any of Roblox Studio's features for starting/stopping games. It's possible that something funny is happening here, like extra copies of Rojo acting strangely in the newly-spawned DataModels.

**Comment by LPGhatguy** [comment] 2020-11-12 00:36
Because we don't have a repro for this issue, I'm going to close this issue. Feel free to re-open this issue if you are still encountering this issue and can help identify what the cause of this issue would be.

**Closed by LPGhatguy** 2020-11-12 00:36 UTC
Labels: status: needs repro, type: bug
