### ISSUE TITLE
Rojo Connecting doesn't work.

### ISSUE THREAD

**Issue by Bulldo344** [rojo-rbx/rojo#428] opened 2021-06-08 14:10 UTC
Whenever I launch Rojo, and try to connect it; it says this error;

![image](https://user-images.githubusercontent.com/53837083/121200436-ba5cb780-c841-11eb-9a4a-1579002120a4.png)

**Comment by LPGhatguy** [comment] 2021-06-08 16:57
Hello, thanks for filing an issue.

This is a duplicate of #400. It's a user configuration issue that has a better error message starting in Rojo 7.

**Closed by LPGhatguy** 2021-06-08 16:57 UTC
