### ISSUE TITLE
Two-Way Sync Deletes Changes and Crashes After

### ISSUE THREAD

**Issue by ghost** [rojo-rbx/rojo#933] opened 2024-06-30 18:11 UTC
### Steps to Reproduce
1. Enable Two-Way Sync in the Settings
![image](https://github.com/rojo-rbx/rojo/assets/173928831/56e2d0b7-a6d9-49a6-b98e-afc0d891bcb6)
2. `rojo serve`
3. Change a Roblox Studio script
4. Click connect

Then your changes will get deleted and it crashes a few seconds later.

```
[ERROR rojo] Rojo crashed!
[ERROR rojo] This is probably a Rojo bug.
[ERROR rojo]
[ERROR rojo] Please consider filing an issue: https://github.com/rojo-rbx/rojo/issues
[ERROR rojo]
[ERROR rojo] Details: called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }
[ERROR rojo] in file src\change_processor.rs on line 229
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by kennethloeffler** [comment] 2024-10-24 17:37
Duplicate of #790

**Closed by kennethloeffler** 2024-10-24 17:37 UTC
