### ISSUE TITLE
Moving folder within partition while live won't sync

### ISSUE THREAD

**Issue by Avigant** [rojo-rbx/rojo#132] opened 2019-03-09 02:10 UTC
If ,on Windows 10, I move a folder inside a partition while sync is live to any other location in any partition, this change won't be synced. Instead, the replicated instance will just be deleted instead of being moved.

I am using v0.5.0 Alpha 5. There is no output from this issue in command line. When I move it *more than once*, I see something like this in Studio output:

```
20:14:40.840 - [Rojo-Warn] Attempted to remove nonexistant ID 556cdb65-e298-4fca-a436-361b11ba5c86
20:14:40.841 - [Rojo-Warn] Attempted to destroy nonexistant ID 556cdb65-e298-4fca-a436-361b11ba5c86
```

**Comment by LPGhatguy** [comment] 2019-03-12 00:01
I'm having trouble reproducing this!

If you can get me a consistent reproduction, can you send me what the server sends back for these URLs? Also, if you could send me your project file, that would help track this down more quickly.

http://localhost:34872/visualize/imfs
http://localhost:34872/visualize/rbx

Because they'll describe the shape of your project pretty precisely, you can send them to me via Discord if they might have something sensitive in them that you don't want on a public issue.

**Comment by Avigant** [comment] 2019-03-12 03:43
`default.project.json`:
```json
{
  "name": "Test",
  "tree": {
    "$className": "DataModel",
    "HttpService": {
      "$className": "HttpService",
      "$properties": {
        "HttpEnabled": {
          "Type": "Bool",
          "Value": true
        }
      }
    },
    "ServerScriptService": {
      "$className": "ServerScriptService",
      "server_code": {
        "$path": "source_code/server"
      }
    },
    "ReplicatedStorage": {
      "$className": "ReplicatedStorage",
      "shared_code": {
        "$path": "source_code/shared"
      }
    }
  }
}```

`rbx`:
```

digraph RojoTree {
    rankdir = "LR";
    graph [
        ranksep = "0.7",
        nodesep = "0.5",
    ];
    node [
        fontname = "Hack",
        shape = "record",
    ];

    "eeba8a4f-8450-45f0-bcf4-5f0cfcc10855" [label="Test|DataModel|eeba8a4f-8450-45f0-bcf4-5f0cfcc10855|\{&quot;ignoreUnknownInstances&quot;:true\}"]
    "eeba8a4f-8450-45f0-bcf4-5f0cfcc10855" -> "f9fe05f2-e1e8-47fc-8ab1-a8a769355750"
    "f9fe05f2-e1e8-47fc-8ab1-a8a769355750" [label="HttpService|HttpService|f9fe05f2-e1e8-47fc-8ab1-a8a769355750|\{&quot;ignoreUnknownInstances&quot;:true\}"]
    "eeba8a4f-8450-45f0-bcf4-5f0cfcc10855" -> "337ee23e-f40d-4bb0-8870-83b20f6796db"
    "337ee23e-f40d-4bb0-8870-83b20f6796db" [label="ServerScriptService|ServerScriptService|337ee23e-f40d-4bb0-8870-83b20f6796db|\{&quot;ignoreUnknownInstances&quot;:true\}"]
    "337ee23e-f40d-4bb0-8870-83b20f6796db" -> "bfcf25a3-462f-4cc7-9567-81f500ecf505"
    "bfcf25a3-462f-4cc7-9567-81f500ecf505" [label="server_code|Folder|bfcf25a3-462f-4cc7-9567-81f500ecf505|\{&quot;ignoreUnknownInstances&quot;:false\}"]
    "bfcf25a3-462f-4cc7-9567-81f500ecf505" -> "99589e97-c03d-41de-aba8-8603f94f05cf"
    "99589e97-c03d-41de-aba8-8603f94f05cf" [label="another_tester|ModuleScript|99589e97-c03d-41de-aba8-8603f94f05cf|\{&quot;ignoreUnknownInstances&quot;:false\}"]
    "eeba8a4f-8450-45f0-bcf4-5f0cfcc10855" -> "714af98a-e855-4cdc-9c59-878b99023bd3"
    "714af98a-e855-4cdc-9c59-878b99023bd3" [label="ReplicatedStorage|ReplicatedStorage|714af98a-e855-4cdc-9c59-878b99023bd3|\{&quot;ignoreUnknownInstances&quot;:true\}"]
    "714af98a-e855-4cdc-9c59-878b99023bd3" -> "63730269-a6bc-4da3-8a35-f3dc306a2eb6"
    "63730269-a6bc-4da3-8a35-f3dc306a2eb6" [label="shared_code|Folder|63730269-a6bc-4da3-8a35-f3dc306a2eb6|\{&quot;ignoreUnknownInstances&quot;:false\}"]
    "63730269-a6bc-4da3-8a35-f3dc306a2eb6" -> "34822505-0ea3-46db-b7e5-5d64b834fc7b"
    "34822505-0ea3-46db-b7e5-5d64b834fc7b" [label="tester|ModuleScript|34822505-0ea3-46db-b7e5-5d64b834fc7b|\{&quot;ignoreUnknownInstances&quot;:false\}"]
}
```

```

digraph RojoTree {
    rankdir = "LR";
    graph [
        ranksep = "0.7",
        nodesep = "0.5",
    ];
    node [
        fontname = "Hack",
        shape = "record",
    ];

    "C:/Users/Name/Documents/Avigant/Rojo Debugging/Test/source_code/server"
    "C:/Users/Name/Documents/Avigant/Rojo Debugging/Test/source_code/server" -> "C:/Users/Name/Documents/Avigant/Rojo Debugging/Test/source_code/server/another_tester"
    "C:/Users/Name/Documents/Avigant/Rojo Debugging/Test/source_code/server/another_tester" [label = "another_tester"]
    "C:/Users/Name/Documents/Avigant/Rojo Debugging/Test/source_code/server/another_tester" -> "C:/Users/Name/Documents/Avigant/Rojo Debugging/Test/source_code/server/another_tester/init.lua"
    "C:/Users/Name/Documents/Avigant/Rojo Debugging/Test/source_code/server/another_tester/init.lua" [label = "init.lua"]
    "C:/Users/Name/Documents/Avigant/Rojo Debugging/Test/source_code/shared"
    "C:/Users/Name/Documents/Avigant/Rojo Debugging/Test/source_code/shared" -> "C:/Users/Name/Documents/Avigant/Rojo Debugging/Test/source_code/shared/tester"
    "C:/Users/Name/Documents/Avigant/Rojo Debugging/Test/source_code/shared/tester" [label = "tester"]
    "C:/Users/Name/Documents/Avigant/Rojo Debugging/Test/source_code/shared/tester" -> "C:/Users/Name/Documents/Avigant/Rojo Debugging/Test/source_code/shared/tester/init.lua"
    "C:/Users/Name/Documents/Avigant/Rojo Debugging/Test/source_code/shared/tester/init.lua" [label = "init.lua"]
}
```

Step 1. Serve.
Step 2. Move `tester` folder from `shared` to be inside `another_tester`.
Step 3. Move `another_tester` back to `shared`.

Should trigger the bug.

Also, I can't view the rbx or imfs files when I am listening to the serve. I have to disconnect or they won't load. Is this intentional, or another bug?

**Comment by LPGhatguy** [comment] 2019-03-12 18:00
Thanks for the repro, I'll get on that today.

Other endpoints not working while the plugin is connected is something I thought might happen in theory. That bug is new in alpha 5 with the change in web server from  Rouille to Hyper, ugh. I'll file another bug for it.

**Comment by LPGhatguy** [comment] 2020-03-14 03:41
This should be fixed in Rojo master, including recent alphas.

**Closed by LPGhatguy** 2020-03-14 03:41 UTC
Labels: regression, type: bug, version: 0.5.x
