### ISSUE TITLE
Two-Way-Sync crashes rojo instance when editing under a protected drive

### ISSUE THREAD

**Issue by 29cmb** [rojo-rbx/rojo#930] opened 2024-06-24 11:12 UTC
I am running on an SD card for my programming, then transferring those files onto my onedrive once finished. I was testing the experimental features and it appears that whenever I make an edit, it does not have permission to make changes and immediately kills the server

```
[ERROR rojo] Rojo crashed!
[ERROR rojo] This is probably a Rojo bug.
[ERROR rojo] 
[ERROR rojo] Please consider filing an issue: https://github.com/rojo-rbx/rojo/issues
[ERROR rojo] 
[ERROR rojo] Details: called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }
[ERROR rojo] in file src\change_processor.rs on line 229
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by seujorgenochurras** [comment] 2024-09-06 20:54
I'm having the same issue

**Comment by kennethloeffler** [comment] 2024-10-24 17:39
Duplicate of #790. I'll also add that this doesn't seem to have anything to do with protected drives, but rather a logic error in the tree event processor around init scripts

**Closed by kennethloeffler** 2024-10-24 17:39 UTC
Labels: type: bug, two-way-sync
