### ISSUE TITLE
RunContext does not work

### ISSUE THREAD

**Issue by PoliceFighter761** [rojo-rbx/rojo#667] opened 2023-04-26 16:59 UTC
When specifying the RunContext property it simply does not get applied. Here is my setup:

![image](https://user-images.githubusercontent.com/53328446/234648175-663cbd50-09b1-4672-afa6-785d6b0b7e94.png)

with the following in the .meta
```json
{
    "properties": {
      "RunContext": {
        "Enum": 2
      }
    }
}
```

Which results in a Script with the RunContext set to legacy instead of Client:
![image](https://user-images.githubusercontent.com/53328446/234648445-7a29136c-9c39-4d45-ac7f-1b7466e8c8ff.png)

In the mean time I have made a work-around extra plugin which applies the RunContext instead. It uses the following code:
```lua
foundClientScript.RunContext = 2;
```
which makes me believe that it can not be a permissions issue because the above code works.

Is there any way I can properly do this with rojo or do I have to wait for the time being? Am I doing something wrong?

I am using Rojo 7.3.0 but it did not work in the version prior either.

**Comment by Zodanim** [comment] 2023-05-13 10:40
I have this issue as well, I'd like to use Rojo but this is impacting the workflow I had when I worked purely in studio which is more efficient for me.

It's been like this for a while, I recall it working at some point but I don't remember when, why or how.

```lua
{
    "properties": {
        "RunContext": {
            "Enum": 2
        }
    }
}
```
<img src="https://github.com/rojo-rbx/vscode-rojo/assets/97851558/5b9efb18-7578-49c3-a637-8e7941a74069" width="30%">

Weirdly enough the RunContext property *does* show up in the Rojo local web portal:
<img src="https://github.com/rojo-rbx/vscode-rojo/assets/97851558/ce601440-0d7b-4e9b-93ad-4bd534e55fe3" width="45%">

Maybe it's an issue with the studio plugin not syncing it in?

**Comment by Ozzypig** [comment] 2023-05-31 23:11
In Rojo 7.2.1, this seems to be working for me:

**Main.server.lua** paired with this **Main.meta.json**:

```json
{
	"properties": {
		"RunContext": "Client"
	}
}
```

**Comment by Zodanim** [comment] 2023-06-01 22:11
> In Rojo 7.2.1, this seems to be working for me:
>
> Main.server.lua paired with this Main.meta.json:
> ```json
> {
> 	"properties": {
> 		"RunContext": "Client"
> 	}
> }
> ```

Weird, I have Rojo 7.2.1 as well. I tried copy-pasting that meta file with files **Some.server.lua** and **Some.meta.json**, I got an unknown property error stopping me from starting Rojo at all:

![image](https://github.com/rojo-rbx/rojo/assets/97851558/c8f70baf-0998-4628-96c1-4d18aa18ef54)

![image](https://github.com/rojo-rbx/rojo/assets/97851558/8c4eced1-17db-4466-a2a4-b884865a153a)

Using the explicit enum format doesn't error and appears in the Rojo tree *(as shown before*) but instead silently doesn't apply to my script, this is all really confusing.

**Comment by sasial-dev** [comment] 2023-06-02 22:22
Fixed in `7.3.0`, this issue can be closed.

**Comment by PoliceFighter761** [comment] 2023-06-02 22:24
When I created the issue, I had already updated it to 7.3.0, and it didn't work. (I stated that in the original issue, too)

**Comment by Zodanim** [comment] 2023-06-03 00:12
> Fixed in `7.3.0`, this issue can be closed.

I updated to 7.3.0 and tried using the implicit format again as such:

```json
{
    "properties": {
        "RunContext": "Client"
    }
}
```

Same file names and setup as before, it no longer crashes like it did when I used 7.2.1, but still RunContext does not get applied:

![image](https://github.com/rojo-rbx/rojo/assets/97851558/88dbe384-b3c9-442a-9383-b8e9bdad64ce)

![image](https://github.com/rojo-rbx/rojo/assets/97851558/28271c89-3576-4fbd-9b80-b4eb7cc88cb0)

The issue persists. :(

**Comment by Barocena** [comment] 2023-06-13 07:15
@Zodanim  @PoliceFighter761 
it works fine on both `serve` and `build`

![image](https://github.com/rojo-rbx/rojo/assets/34089907/7917d8bc-b6e2-4cb6-ac2a-0ec0ac90d3bb)

**Comment by GammaWhiskey** [comment] 2023-06-21 02:42
Found out why this issue is only happening to some people:

I had this issue when using the Roblox model version of the plugin, but switching to the plugin version managed by the VS Code extension fixed the issue.

**Comment by kennethloeffler** [comment] 2023-06-22 00:16
> Found out why this issue is only happening to some people:
> 
> I had this issue when using the Roblox model version of the plugin, but switching to the plugin version managed by the VS Code extension fixed the issue.

Hey @GammaWhiskey, does this happen with the [plugin on GitHub releases](https://github.com/rojo-rbx/rojo/releases/tag/v7.3.0)? [The one on Roblox.com](https://www.roblox.com/library/6415005344/Rojo-7)? Both?

**Comment by GammaWhiskey** [comment] 2023-06-22 14:01
Happens with the one on Roblox.com, not the plugin on GitHub releases

**Comment by PoliceFighter761** [comment] 2023-06-25 10:35
Can confirm that this only happens [on the toolbox plugin](https://www.roblox.com/library/6415005344/Rojo-7). After installing the plugin [on the release page](https://github.com/rojo-rbx/rojo/releases/tag/v7.3.0) RunContext gets properly synced.

**Comment by Zodanim** [comment] 2023-07-05 08:21
I got a chance to test the plugin on the GitHub releases page just now and can confirm the issue is gone, thanks everyone!

![image](https://github.com/rojo-rbx/rojo/assets/97851558/ec8ba2f5-aac4-465b-b7ea-ed2c5d8ca0be)

**Closed** 2023-07-10 00:12 UTC

**Comment by ambergamefam** [comment] 2023-07-24 18:54
@LPGhatguy Can you look into updating the Roblox plugin? This has caused a bunch of confusion, and makes it hard to want to make the switch to RunContext when people will sync up your source code incorrectly.

**Comment by Dekkonot** [comment] 2023-07-24 21:13
@ambergamefam LPG is no longer contributing to Rojo, so the existing plugin likely won't be updated. We have a new plugin located [here](https://www.roblox.com/library/13916111004/Rojo) that people should install and the documentation on Rojo's website has been updated to reflect that. I know that it's frustrating, and it's not the solution we would have liked, but it is what it is. ☹️ 

To prevent this from ever becoming an issue again, the new plugin is published by a Roblox group rather than any one user, so if Boatbomber, me, or anyone else step away from Rojo it won't impact users again. That's unfortunately all we can do.

**Comment by ambergamefam** [comment] 2023-07-26 20:03
Oh, gotcha! Was confused since the old plugin is named "Rojo 7" and Rojo is still in version 7.

<img width="588" alt="image" src="https://github.com/rojo-rbx/rojo/assets/122126644/1bd7284c-4516-4d70-964d-53c806e01e4e">
I'm noticing the new Rojo plugin has a moderated thumbnail, just FYI.

**Comment by boatbomber** [comment] 2023-07-26 20:57
That's just Roblox being Roblox. The image is fine, but various pages you view have issues.

Dashboard Page:
![image](https://github.com/rojo-rbx/rojo/assets/40185666/45149d9e-3771-4cd9-bb6f-8cfc88395810)

Marketplace Page:
![image](https://github.com/rojo-rbx/rojo/assets/40185666/42ad899a-2843-4e87-9bbf-a4168fa5c2b4)

Library Page:
![image](https://github.com/rojo-rbx/rojo/assets/40185666/79771900-4346-4d5f-a97d-97478de6d342)
