### ISSUE TITLE
Allow comments in json file

### ISSUE THREAD

**Issue by GlowingUmbreon** [rojo-rbx/rojo#426] opened 2021-05-26 22:30 UTC
Currently its impossible to put comments into a json file, using a format like [jsonc](https://komkom.github.io/) will allow for comments and allow for a much easier time documenting model.json and project.json files.

**Comment by Kampfkarren** [comment] 2021-05-26 23:44
Duplicate of #207

**Closed** 2021-05-27 04:53 UTC
Labels: duplicate
