### ISSUE TITLE
address already in use

### ISSUE THREAD

**Issue by ryanlego** [rojo-rbx/rojo#302] opened 2020-03-14 23:03 UTC
Rojo server listening on port 34872
**thread 'main' panicked at 'error binding to 127.0.0.1:34872: error creating server listener: Address already in use (os error 48)', /Users/thisismyname/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/server/mod.rs:116:17**
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR rojo] Rojo crashed!
[ERROR rojo] This is a bug in Rojo.
[ERROR rojo] 
[ERROR rojo] Please consider filing a bug: https://github.com/LPGhatguy/rojo/issues
[ERROR rojo] 
[ERROR rojo] **Details: error binding to 127.0.0.1:34872: error creating server listener: Address already in use (os error 48)**

It says address is already in use, but it thinks that I've had it on for a while even though I restarted everything, is this really a bug?

**Comment by LPGhatguy** [comment] 2020-03-14 23:25
I believe this is not a bug itself, but just us handling an unrecoverable error poorly and crashing instead of exiting gracefully.

The error message is accurate. You probably do have some other Rojo server running on that port. Sometimes you might need to restart your terminal, your editor, or even your computer if you're unable to find the process with that port open.

I'll make sure Rojo exits gracefully when a port is already in use, if possible!

**Comment by ryanlego** [comment] 2020-03-14 23:35
I wish I could just exit my editor, or restart my terminal, but I had to restart my laptop to fix the issue. Haha lol, I wish the process was automatic and was removed upon qutting of the editor.

**Comment by JoelDesante** [comment] 2020-05-05 22:07
**For Mac Users, the solution to this when it occurs goes as follows:**
1. In the terminal type the command `lsof -i :34872` (assuming you are on the default port)
2. Look for the first `rojo` PID, it should look something like this 
`rojo      25247 username    3u  IPv4 xxxxxxxxxxxxxxxxxx      0t0  TCP localhost:34872 (LISTEN)`
The PID in this case is `25247`
3. Now, run the command `kill -9 25247` where "25247" is the PID that your computer displayed.

After doing this, click the Start Rojo button and crack on with what you were doing.

**Comment by ryanlego** [comment] 2020-05-05 22:23
@JoelDesante Thank you for your solution, the terminal commands are unnecessary as I can simply just restart my laptop. Nonetheless, it's a minor issue and I appreciate you for giving me a solution based on just command-prompts.

**Comment by JoelDesante** [comment] 2020-05-15 16:43
@ryanlego Are you using VSCode by any chance?

**Comment by ryanlego** [comment] 2020-05-15 21:43
Yes, I am. @JoelDesante

**Comment by JoelDesante** [comment] 2020-05-16 19:43
@ryanlego 

I've made a pull request to the VSCode plugin for Rojo which should hopefully fix this issue. If it's acceptable to the maintainer, it turns out it was able to be fixed with just one line of code.

https://github.com/rojo-rbx/vscode-rojo/pull/28

**Closed** 2023-10-03 21:40 UTC
Labels: type: bug, size: small, impact: small
