### ISSUE TITLE
Disconnecting from Rojo server with Studio plugin makes plugin display an error message

### ISSUE THREAD

**Issue by Aerodymier** [rojo-rbx/rojo#441] opened 2021-07-05 23:48 UTC
When I disconnect from Rojo server with Roblox Studio plugin by clicking on the "X" button for plugin (no, not the window button) makes it display an error, either HTTP request fail or server isn't running error. It's a minor bug but it's a bug.

Version: 7.0.4

**Comment by LPGhatguy** [comment] 2021-07-12 16:46
Hello, thank you for filing an issue!

I am closing this as a duplicate of #380.

**Closed by LPGhatguy** 2021-07-12 16:46 UTC
