### ISSUE TITLE
Rojo plugin breaks when trying to sync MeshParts

### ISSUE THREAD

**Issue by vocksel** [rojo-rbx/rojo#286] opened 2020-01-07 19:13 UTC
When a Rojo project includes a model file containing a MeshPart, the Rojo plugin disconnects when trying to sync the project. The following is the warning I get in the output:

```
14:07:40.190 - [Rojo-Warn] Rojo session terminated because of an error:
14:07:40.216 - [Rojo-Warn] Plugin_rojo.rbxm.Rojo.Plugin.Reconciler:67: Invalid property MeshPart.MeshId: Error(Roblox: Unable to assign property MeshId. Script write access is restricted
14:07:40.218 - [Rojo-Warn] Plugin_rojo.rbxm.Rojo.RbxDom.PropertyDescriptor:19 function set
14:07:40.219 - [Rojo-Warn] Plugin_rojo.rbxm.Rojo.RbxDom.PropertyDescriptor:58 function write
14:07:40.219 - [Rojo-Warn] Plugin_rojo.rbxm.Rojo.Plugin.setCanonicalProperty:21 function setCanonicalProperty
14:07:40.220 - [Rojo-Warn] Plugin_rojo.rbxm.Rojo.Plugin.Reconciler:67 function reconcile
14:07:40.222 - [Rojo-Warn] Plugin_rojo.rbxm.Rojo.Plugin.Reconciler:96 function reconcile (x2)
14:07:40.237 - [Rojo-Warn] Plugin_rojo.rbxm.Rojo.Plugin.Session:35
14:07:40.238 - [Rojo-Warn] )
```

The behavior I would expect, until `MeshId` can be manipulated by plugins, is for the MeshPart to be skipped over, instead of the plugin failing to sync at all.

I'm using Rojo 0.5.3, with the Rojo.rbxm file downloaded from the [releases page]( https://github.com/rojo-rbx/rojo/releases/tag/v0.5.3).

Repro steps:

- Unpack the following project: [mesh-error.zip](https://github.com/rojo-rbx/rojo/files/4032063/mesh-error.zip)
- Run the following commands from the project folder:
  ```
  $ rojo build -o place.rbxlx
  $ rojo serve
  ```
- Open the place file, and attempt to sync in with the plugin.

You should get the same warning as above.

**Comment by LPGhatguy** [comment] 2020-01-07 19:18
I think this is a duplicate of #230, maybe unintuitively.

I should be able to put together a 0.5.4 release with the latest version of the reflection database to fix this.

**Closed by LPGhatguy** 2020-01-07 19:18 UTC
Labels: type: bug, version: 0.5.x
