### ISSUE TITLE
Rojo deletes any child of the script if it is renamed

### ISSUE THREAD

**Issue by VinDotRun** [rojo-rbx/rojo#506] opened 2021-12-08 16:29 UTC
Apparently Rojo deletes any and all child that a script may have if they are not defined in the project.json file. I had inserted a `ScreenGui` as parent of a `LocalScript`. When I renamed the script in VS Code, Rojo deleted the `ScreenGui`.
I don't know if it's a bug or just a configuration issue on my end.

**Comment by VernandoGames** [comment] 2021-12-08 18:59
I believe this would be fixed by creating a file in the same directory of that script named ``scriptname.meta.json`` containing the following:
```json
{
    "ignoreUnknownInstances": true
}
```
However, I suggest avoiding having assets directly under script instances and instead have a separate ``Assets`` folder for holding the files. (That's what I do, at least)

**Comment by VinDotRun** [comment] 2021-12-09 18:36
> I believe this would be fixed by creating a file in the same directory of that script named `scriptname.meta.json` containing the following:
> 
> ```json
> {
>     "ignoreUnknownInstances": true
> }
> ```
> 
> However, I suggest avoiding having assets directly under script instances and instead have a separate `Assets` folder for holding the files. (That's what I do, at least)

Even if I use `ignoreUnknownInstances` or create a separated folder, it always deletes the gui whenever Rojo connection is stablished.

**Comment by VinDotRun** [comment] 2021-12-09 18:50
> I believe this would be fixed by creating a file in the same directory of that script named `scriptname.meta.json` containing the following:
> 
> ```json
> {
>     "ignoreUnknownInstances": true
> }
> ```
> 
> However, I suggest avoiding having assets directly under script instances and instead have a separate `Assets` folder for holding the files. (That's what I do, at least)

Creating the meta file seems to have fixed it. Still weird that stuff was being deleted since `$ignoreUnknownInstances` is set to true on all classes inside my `project.json` file.

**Comment by havi11** [comment] 2021-12-11 00:04
make a folder, name it the script name, rename the script init.client/server.luau, then put the file in the folder.

**Comment by boatbomber** [comment] 2022-07-25 17:58
I believe this is behaving as intended. Setting `ignoreUnknownInstances` resolves this, as it should.

**Closed by boatbomber** 2022-07-25 17:58 UTC
