### ISSUE TITLE
Rojo tries to write directly to folder

### ISSUE THREAD

**Issue by SUMER9999dev** [rojo-rbx/rojo#822] opened 2023-12-16 18:27 UTC
Two-way sync is enabled.
repro: just try to write anything in roblox studio inside the ModuleScript under which there is anything.

analysis:
in the rojo panel, you can see that the instigating source points to the folder, and not to the script itself, but I thought this was normal
![chrome_nDpNnqfrX4](https://github.com/rojo-rbx/rojo/assets/59053498/ce2ef8b8-a948-42f7-89fa-6847d72f6c08)
the error is created in src/change_processor.rs at line 203
![chrome_QT3uXJSZrt](https://github.com/rojo-rbx/rojo/assets/59053498/063a0a63-a235-41cb-8da7-ccca0f07d0b1)
console crash
![cmd_sOYmbxwo11](https://github.com/rojo-rbx/rojo/assets/59053498/e90f5909-9e75-4836-8350-8cbcc1552345)

**Comment by kennethloeffler** [comment] 2024-03-30 22:15
Closing as a duplicate of #790, we'll track this bug there

**Closed by kennethloeffler** 2024-03-30 22:15 UTC
Labels: type: bug, scope: cli, two-way-sync
