### ISSUE TITLE
ImageLabel SliceCenter Not Replicating

### ISSUE THREAD

**Issue by TheQuinnn** [rojo-rbx/rojo#201] opened 2019-06-20 13:57 UTC
When using a `.rbxmx` file within a project, the `SliceCenter` property of a `ImageLabel` instance isn't replicating correctly. It is being set to `0, 0, 0, 0` rather than the true value within the `.rbxmx` file.

No errors/warnings are being outputted inside of the Roblox Studio console or the command prompt.

Also tried using a `.rbxm` file to see what would happen in this case (just to see if I could provide any more information. I know full support for `.rbxm` files is still in the works), and it is missing the property entirely, as the `ScaleType` is being set to `Stretch`.

**Comment by LPGhatguy** [comment] 2019-06-20 18:21
It looks like there are a few missing properties I didn't catch when working on the dump, Rect being one of them!

**Comment by LPGhatguy** [comment] 2019-06-21 01:26
Should be fixed in the next release, thanks!

**Comment by TheQuinnn** [comment] 2019-07-21 14:25
Doesn't appear to be fixed in Alpha 12. Possibly worth looking into again?

**Comment by LPGhatguy** [comment] 2019-07-21 19:48
Sure thing! I'll go through and try to reproduce this and a couple other bugs on Monday.

**Comment by Sleitnick** [comment] 2019-08-21 20:37
Is there any update on this? I am experiencing this bug. Using v0.5.0-alpha.13

**Comment by LPGhatguy** [comment] 2019-08-21 22:45
I was able to reproduce this, I just checked a test project into Rojo that demonstrates the issue. I'm tracking the cause right now, it looks like it's lost over the protocol.

**Closed** 2019-08-21 23:00 UTC
Labels: type: bug

**Comment by LPGhatguy** [comment] 2019-08-21 23:08
This should be fixed in the next release, or you can build the plugin from the repository using Rojo itself:

```bash
rojo build plugin -o Rojo.rbxm
```
