### ISSUE TITLE
High CPU usage on MacOS

### ISSUE THREAD

**Issue by jackTabsCode** [rojo-rbx/rojo#815] opened 2023-11-09 01:34 UTC
CPU usage hovering around 33%. 
<img width="1040" alt="image" src="https://github.com/rojo-rbx/rojo/assets/44332148/c60e509b-5cf4-4c67-8efc-e1fdd435acb0">

Some notes:
- macOS Sonoma 14.1.1
- Studio is not running
- Persistent after a fresh restart
- Memory usage is low
- Rojo version 7.4.0-rc.3. Does not occur on 7.3.0
- MacBook M2 Pro

**Comment by filiptibell** [comment] 2023-11-09 07:33
I'm seeing similar high CPU usage using latest macOS and Rojo. Worth noting here, in case it is not obvious for someone not familiar with macOS or Activity Monitor - this is saying ~ 35% of *one cpu core*. Which is still higher than it should be, but is also (imo) ok if it means the latest Rojo version *actually works* on macOS compared to previous ones.

**Comment by jackTabsCode** [comment] 2023-11-09 17:47
> I'm seeing similar high CPU usage using latest macOS and Rojo. Worth noting here, in case it is not obvious for someone not familiar with macOS or Activity Monitor - this is saying ~ 35% of _one cpu core_. Which is still higher than it should be, but is also (imo) ok if it means the latest Rojo version _actually works_ on macOS compared to previous ones.

Sure, but seeing as Rojo 7.3.0's performance shows 0.0% usage, I don't think it's something that should be overlooked. 
![image](https://github.com/rojo-rbx/rojo/assets/44332148/00620763-32f6-417c-afe0-055863584e34)

**Comment by Dekkonot** [comment] 2023-11-09 18:59
My ability to diagnose the cause of this is rather limited because I don't own any Mac devices. That said, there's only a few changes we made that may be the cause of this. To rule out the obvious, can either of you (optimistically you, @filiptibell, since I know you have a Rust compiler installed already) test using a build made on d7277b5a5b3e1c57709c3cdf0c920b9b84f9bd8c? If it's a problem with that build, it rules out our change to the backend file watcher.

If it *isn't* a problem with that build, it's almost certainly related to #783 and there's not much we can do beyond look into switching to a new file watcher entirely. If that ends up being the case, it'll probably have to wait until after 7.4 releases since it's a surprisingly complex problem.

**Comment by filiptibell** [comment] 2023-11-09 21:00
Just checked out https://github.com/rojo-rbx/rojo/commit/d7277b5a5b3e1c57709c3cdf0c920b9b84f9bd8c and it definitely does not have the high CPU usage issue:

![CleanShot 2023-11-09 at 21 52 20@2x](https://github.com/rojo-rbx/rojo/assets/9497781/318a748d-948b-4955-93f9-44c4e5cae32f)

So it does seem like notify / the file watcher is the culprit. I agree that a `7.4.0` release where everything is at least working should be prioritized and that we can look at solutions to this high cpu usage after release.

**Comment by kennethloeffler** [comment] 2023-11-10 08:04
For context, previous versions of Rojo could take minutes to even start a serve on macOS: https://github.com/rojo-rbx/rojo/issues/609. This seems like an issue in [notify's](https://github.com/notify-rs/notify) kqueue backend, but we have not yet narrowed down the root cause. The high latency seems to be resolved by [using polling on macOS instead of kqueue](https://github.com/rojo-rbx/rojo/pull/783). Naturally, this results in higher CPU usage. 

We have tried upgrading notify, and it does not improve the kqueue backend's high latency. It's possible that notify 6's polling implementation uses fewer resources than notify 4, but we haven't yet tested this or looked very closely at it, and frankly, I'm pessimistic. 

Notify seems like it needs some serious work if it's going to work for Rojo. Failing that, we may need to switch to a different file watcher.

**Closed** 2024-01-02 17:26 UTC
Labels: type: bug, scope: cli, version 7.4
